数据预处理的练习

In [8]:
import os
import torch

In [9]:
os.makedirs(os.path.join("./data"), exist_ok = True)
data_file = os.path.join(os.path.join("./data"), "house_price.csv")
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [10]:
import pandas as pd

In [11]:
data = pd.read_csv(data_file)

In [12]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]

In [13]:
inputs = pd.get_dummies(inputs, dummy_na = True)

In [14]:
x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x, y

(tensor([[nan, 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [nan, 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [ ]:
a = torch.arange(20).reshape(5, 4)

In [27]:
a, a.cumsum(axis = 1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  3,  6],
         [ 4,  9, 15, 22],
         [ 8, 17, 27, 38],
         [12, 25, 39, 54],
         [16, 33, 51, 70]]))