数据操作的练习

In [1]:
import torch

In [2]:
x = torch.arange(12, dtype = torch.float32).reshape(3,4)
y = torch.arange(12,24, dtype = torch.float32).reshape(3,4)

In [3]:
torch.cat((x, y), dim = 0), torch.cat((x, y), dim = 1) #0维合并指的是合并行,1唯合并指的是和并列

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]),
 tensor([[ 0.,  1.,  2.,  3., 12., 13., 14., 15.],
         [ 4.,  5.,  6.,  7., 16., 17., 18., 19.],
         [ 8.,  9., 10., 11., 20., 21., 22., 23.]]))

In [10]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])