In [1]:
import torch
from torch import nn
from d2l import torch as d2l

池化层的正向操作

In [7]:
def pool2d(x, pool_size, mode = "max"):
    p_h, p_w = pool_size
    y = torch.zeros([x.shape[0] - p_h + 1, x.shape[1] - p_w + 1])

    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            if mode == "max":
                y[i, j] = x[i:i+p_h, j:j+p_w].max()
            elif mode == "avg":
                y[i, j] = x[i:i+p_h, j:j+p_w].mean()

    return y

In [12]:
x = torch.tensor([[1.,2.,3.],
                  [4.,5.,6.],
                  [7.,8.,9.]])
pool2d(x, [2,2], "max"), pool2d(x, [2,2], "avg")

(tensor([[5., 6.],
         [8., 9.]]),
 tensor([[3., 4.],
         [6., 7.]]))

深度学习框架中池化层步长与窗口大小相同

In [22]:
pooling_x = torch.arange(16, dtype = torch.float32).reshape(1, 1, 4, 4)

In [23]:
net = nn.MaxPool2d(3)

In [24]:
net(pooling_x)

tensor([[[[10.]]]])

多通道池化层

In [25]:
pooling_x = torch.cat((pooling_x, pooling_x + 1), 1) #dim代表在哪个维度上合并
pooling_x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [26]:
net2 = nn.MaxPool2d(2)
net2(pooling_x)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])